version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  style:
    executor:
      name: node/default
      tag: "18.19.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Check code style
          command: yarn format
  test:
    executor:
      name: node/default
      tag: "18.19.0"
    steps:
      - checkout

      - run:
          name: Install pnpm package manager
          command: sudo npm install -g pnpm

      - run:
          name: Install deps
          command: pnpm -w install

      - run:
          name: Build workspace packages
          # build pkgs in deps order
          command: pnpm build core

      - run:
          name: Run tests
          command: pnpm test

workflows:
  ci:
    jobs:
      - style
      - test
